name: Docker Image CI

on:
  push:
    branches: [ master ]


jobs:

  build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image for nginx
        run: docker build -t samrajpur/multi-nginx ./nginx

     
    

      
