name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for client
      run: docker build -t samrajpur/multi-client ./client 

    - name: Build the Docker image for nginx
      run: docker build -t samrajpur/multi-nginx ./nginx
      
    - name: Build the Docker image for server
      run: docker build -t samrajpur/multi-server ./server
    
    - name: Build the Docker image for worker
      run: docker build -t samrajpur/multi-worker ./worker
      
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: samrajpur/multi-docker-hub-repo
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

     
    

      
